
name: AutoBuild

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64, arm, arm64]
    steps:
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 32GB
          maximum-size: 32GB
          disk-root: "C:"


      - name: Checkout
        uses: actions/checkout@v3


      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1


      - name: Build
        run: msbuild /m /t:Yttrium /restore /p:AppxBundlePlatforms=${{ matrix.architecture }} /p:AppxBundle=Always /p:UapAppxPackageBuildMode=Sideload /p:AppxPackageDir=root/artifacts/platform-config/ /p:AppxPackageSigningEnabled=false /p:Configuration=Release Yttrium.sln
        env:
          MsixBundle: Always
          BuildMode: SideloadOnly
          Configuration: Release


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yttrium
          path: root/artifacts/platform-config/
