
name: AutoBuild

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64, arm, arm64]
    steps:
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 32GB
          maximum-size: 32GB
          disk-root: "C:"


      - name: Checkout
        uses: actions/checkout@v3


      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1


      - name: Build UWP utilities
        run: msbuild /m /t:Yttrium /restore /p:Platform=${{ matrix.architecture }} /p:MsixBundle=$env:MsixBundle /p:MsixBundlePlatforms="${{ matrix.architecture }}" /p:MsixPackageDir=${{ github.workspace }}\artifacts\win-${{ matrix.architecture }} /p:MsixPackageSigningEnabled=false /p:RuntimeIdentifier=win-${{ matrix.architecture }} /p:PublishDir=${{ github.workspace }}\artifacts\win-${{ matrix.architecture }}/UWP /p:PublishSingleFile=true /p:Configuration=Release Yttrium.sln
        env:
          AppxBundle: Always
          BuildMode: SideloadOnly
          Configuration: Release


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: win-${{ matrix.architecture }}
          path: ${{ github.workspace }}/artifacts/win-${{ matrix.architecture }}
