
name: AutoBuild

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        architecture: [x86, x64, arm64]
    steps:
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.2
        with:
          minimum-size: 32GB
          maximum-size: 32GB
          disk-root: "C:"


      - name: Checkout
        uses: actions/checkout@v3


      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1


      - name: Build
        run: |
          msbuild /t:build -restore Yttrium.sln /p:Platform="x64|x86|arm64" /p:Configuration="Release" /p:AppxBundle="Always" /p:AppxBundlePlatforms="x64|x86|arm64|" /p:AppxPackageDir="$pwd\build" /p:UapAppxPackageBuildMode="SideloadOnly" 


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: yttrium
          path: root/artifacts/platform-config/
